version: '3'
services: 
  todotests:
    image: todotests
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
    networks:
      - app-network
  todofront:
    image: todofrontend
    ports:
      - "3000:3000"
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    networks:
      - app-network
    restart: on-failure
  todoback:
    image: todobackend
    ports:
      - "3001:3001"
    networks:
      - app-network
networks:
  app-network:
